config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get '/home', to: 'home#index'
get '/halo/:id', to: 'home#halo'


resources :books do
	get :active, on: :collection
	patch :toggle, on: :member
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :page, presence: true, numericality: true
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	#index get
	def index
		@books = Book.all
	end

	#show get
	def show
		@book = Book.find(params[:id])
	end

	#new get
	def new
		@book = Book.new
	end

	#create post
	def create
		#render plain: params.inspect
		@book = Book.new(resource_params)
		if @book.save
		render plain:'berhasil menyimpan buku baru'
	else
		render 'new'
	end
	end

	#edit get
	def edit
		@book = Book.find(params[:id])
	end

	#update patch / put
	def update
		@book = Book.find(params[:id])
		@book.update(resource_params)
		render plain:'berhasil edit buku'
	end

	#destroy delete
	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		render plain:'berhasil meghapus buku'
	end

	def active
		@books = Book.where(status: 1)
		render 'index'
	end

	def toggle
		@book = Book.find(params[:id])
		@book.status = 0
		@book.save
		render plain: 'buku berhasil di nonaktifkan'
	end

	private 
	def resource_params
		params.require(:book).permit(:title, :page, :description)
	end

	

	

	

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 	def index
 		@langs = ['ruby','php','java','go','phyton']
 		@title = 'Programming language'

 		@books = Book.all
 	end

 	def halo
 		id = params[:id]
 		book = Book.find_by id: id
 		if book 
 		@title = book.title
 		else
 		@title = 'tidak ditemukan'
 	end
 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<%= form_for(@book) do |f| %>
<div>
	<%= f.label :title %>
	<%= f.text_field :title %>
</div>
<div>
	<%= f.label :page %>
	<%= f.text_field :page %>
</div>
<div>
	<%= f.label :description %>
	<%= f.text_area :description %>
</div>
<div>
	<%= f.submit %>
</div>
<% end %>

app/views/books/index.html.erb
<% @books.each do |b| %>
<div>
	<div><%= b.title %></div>
	<div><%= b.page %></div>
	<div><%= b.status %></div>
	<div><%= b.description %></div>
	<div><%= link_to "Show Book", book_path(b) %> <%= link_to "edit Book", edit_book_path(b) %> <%= link_to "delete Book", book_path(b), method: :delete %> <%= link_to "non-aktif", toggle_book_path(b), method: :patch %></div>
	<hr>
</div>
<%end%>

<%= link_to "New Book", new_book_path %>
<%= link_to "Active Book", active_books_path %>

app/views/books/new.html.erb
<% if @book.errors.any? %>
	<div>
		<% @book.errors.full_messages.each do |message| %>
		<div><%= message %></div>
		<% end %>	
		</div>
<% end %>
<%= form_for(@book) do |f| %>
<div>
	<%= f.label :title %>
	<%= f.text_field :title %>
</div>
<div>
	<%= f.label :page %>
	<%= f.text_field :page %>
</div>
<div>
	<%= f.label :description %>
	<%= f.text_area :description %>
</div>
<div>
	<%= f.submit "submit"%>
</div>
<% end %>

app/views/books/show.html.erb
<%= @book.title %>

app/views/home/halo.html.erb
<h1>halo</h1>
<h2><%=@title%></h2>

app/views/home/index.html.erb
<h1>INDEX</h1>
<h2><%=@title%></h2>

<ul>
	<% @langs.each do |lang| %>
	<li><%=lang %></li>
	<% end %>
	
</ul>

<table>
	<tr>
		<td>id</td>
		<td>title</td>
		<td>page</td>
		<td>description</td>
	</tr>
	<% @books.each do |book| %>
	<tr>
		<td><%= book.id %></td>
		<td><%= book.title %></td>
		<td><%= book.page %></td>
		<td><%= book.description %></td>
	</tr>
	<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>